  const HMAC_KEY_MATERIAL = 'csp-v1-social-proof';

  function b64urlDecode(s) {
    s = s.replace(/-/g, '+').replace(/_/g, '/');
    while (s.length % 4) s += '=';
    const bin = atob(s);
    return Uint8Array.from(bin, c => c.charCodeAt(0));
  }

  function b64url(buf) {
    return btoa(String.fromCharCode(...new Uint8Array(buf)))
      .replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
  }

  function showInvalid(msg) {
    document.getElementById('result').innerHTML = `
      <div class="card err">
        <div class="icon">✗</div>
        <div class="status">Not Verified</div>
        <div class="desc">${msg}</div>
      </div>`;
  }

  function showVerified(payload) {
    const typeColors = {
      SWAP: '#818cf8', BUY: '#22c55e', SELL: '#ef4444',
      SEND: '#ef4444', RECEIVE: '#22c55e', STAKE: '#c084fc'
    };
    const typeColor = typeColors[payload.t] || '#9ca3af';

    let detailsHtml = '';
    if (payload.t === 'SWAP' && payload.p && payload.s) {
      detailsHtml = `
        <div class="detail-row"><span class="dk">Sold</span><span class="dv red">${payload.p}</span></div>
        <div class="detail-row"><span class="dk">Received</span><span class="dv green">${payload.s}</span></div>`;
    } else if (payload.p) {
      const isIncoming = ['BUY','RECEIVE','STAKE'].includes(payload.t);
      detailsHtml = `
        <div class="detail-row"><span class="dk">Amount</span><span class="dv ${isIncoming ? 'green' : 'red'}">${payload.p}</span></div>`;
    }

    document.getElementById('result').innerHTML = `
      <div class="card ok">
        <div class="icon">✓</div>
        <div class="status">Verified</div>
        <div class="desc">This card was generated by CryptoSocialProof</div>
        <div class="badge" style="color:${typeColor};border:1px solid ${typeColor}40">${payload.t}</div>
        ${detailsHtml || payload.p ? `<div class="details">${detailsHtml}
          ${payload.d ? `<div class="detail-row"><span class="dk">Date</span><span class="dv">${payload.d}</span></div>` : ''}
        </div>` : ''}
        <div class="note">This confirms the card was created by this tool from a real parsed transaction. The underlying transaction and wallet address remain private.</div>
      </div>`;
  }

  async function verifyCard() {
    const hash = window.location.hash.slice(1);
    if (!hash) {
      showInvalid('No verification data found. Please scan or open the full QR code link.');
      return;
    }

    const dot = hash.lastIndexOf('.');
    if (dot === -1) {
      showInvalid('Malformed verification link.');
      return;
    }

    const payloadB64 = hash.slice(0, dot);
    const hmacB64    = hash.slice(dot + 1);

    let json;
    try {
      const payloadBytes = b64urlDecode(payloadB64);
      json = new TextDecoder().decode(payloadBytes);
    } catch (e) {
      showInvalid('Could not decode verification data.');
      return;
    }

    let key;
    try {
      const enc = new TextEncoder();
      key = await crypto.subtle.importKey(
        'raw', enc.encode(HMAC_KEY_MATERIAL),
        { name: 'HMAC', hash: 'SHA-256' },
        false, ['sign']
      );
      const sigBuf   = await crypto.subtle.sign('HMAC', key, enc.encode(json));
      const expected = b64url(sigBuf);

      if (hmacB64 !== expected) {
        showInvalid('Verification failed — this card may have been tampered with or was not generated by CryptoSocialProof.');
        return;
      }
    } catch (e) {
      showInvalid('Your browser does not support the verification algorithm. Please try a modern browser.');
      return;
    }

    let payload;
    try {
      payload = JSON.parse(json);
    } catch (e) {
      showInvalid('Could not parse verification data.');
      return;
    }

    showVerified(payload);
  }

  verifyCard();
